const products = [
    {
        id:1,
        title: "Equipo AMD Athlon 3000G Gamer – Radeon™ Vega 3 Graphics",
        description: "Gabinete Perseo Cp3 Rgb. Fuente Eagle Warrior 600w 80 Plus. Biostar A320 – Sata III – USB 3.0. Procesador AMD Athlon 3000G 3,5Ghz 2 núcleos – 4 hilos. Memoria Kingston 8Gb DDR4 3200mhz. Disco WD/Seagate 1TBGráficos Radeon™ Vega 3",
        category: "Computadoras",
        price: 375,
        image: 'amd0.jpg',
        stock: 6,
        inCart: 0,
    },
    {
        id:2,
        title: "Equipo AMD Ryzen 5 5500 Full Gamer – 16gb – SSD – RX6500XT",
        description: "Gabinete EAGLE WARRIOR LOOP RGB con fan trasero Fuente TC ARMY 500w 80 Plus Mother Asrock / Biostar B550MH – Sata III – USB 3.0 Procesador AMD Ryzen 5 5500 6 núcleos 12 hilos 3.6GHz / 4.2GHz Memoria Kingston 16Gb DDR4 3200mhz (2×8) Disco SSD 240Gb + Seagate / WD sata III 1Tb Gráficos Radeon RX6500XT",
        category: "Computadoras",
        price: 1075,
        image: 'amd2.jpg',
        inCart: 0,
        stock: 10,
    },
    {
        id:3,
        title: "Equipo Intel Core I5 11400f Pro Gamer – 16Gb 3200mhz – SSD – RTX3050",
        description: "Gabinete Antec NX220 ARGB + fan con Led Fuente Antec CSK 550w 80 Plus Bronze Mother Gigabyte / Biostar B550 4 bancos de memoria –  soporte SSD PCIe – Sata III – USB 3.0 Procesador AMD Ryzen 5 5600X 3,7 / 4,6Ghz 6 núcleos – 12 hilos Memoria Kingston 16Gb DDR4 3200mhz (2 x 8Gb) Disco SSD 240  + WD Sata III 1Tb Gráficos Geforce RTX2060",
        category: "Computadoras",
        price: 1250,
        image: 'amd1.jpg',
        inCart: 0,
        stock: 20,
    },
    {
        id:4,
        title: "Equipo AMD Ryzen 5 5600X Full Gamer – 16gb – SSD – RTX3060",
        description: "Gabinete Antec NX220 ARGB + fan con Led Fuente Antec CSK 650w 80 Plus Bronze Mother Gigabyte / Biostar B550 4 bancos de memoria –  soporte SSD PCIe – Sata III – USB 3.0 Procesador AMD Ryzen 5 5600X 3,7 / 4,6Ghz 6 núcleos – 12 hilos Memoria Kingston 16Gb DDR4 3200mhz (2 x 8Gb) Disco SSD 240  + WD Sata III 1Tb Gráficos Radeon RX6600XT",
        category: "Computadoras",
        price: 1650,
        image: 'amd3.jpg',
        inCart: 0,
        stock: 13,
    },
    {
        id:5,
        title: "Equipo AMD Ryzen 9 5900X Full Gamer 32gb + SSD + RTX3080",
        category: "Computadoras",
        description: "Gabinete Antec NX800 ARGB – incluye 3 fanes Fuente Cooler Master MWE 850W 80 Plus Gold Full Modular Mother Asus TUF B550M Gaming con 4 bancos DDR4 hasta 128Gb – soporte m.2 PCIe Procesador AMD Ryzen 9 5900X 12 núcleos 24 hilos 3,7 / 4,8Ghz + Watercooling Antec Neptune 240 Memoria Kingston Fury Beast 32Gb DDR4 3200mhz (2 x 16Gb) Disco SSD 1Tb M.2 PCIe Gráficos Geforce RTX3080",
        price: 3500,
        image: 'amd4.jpg',
        inCart: 0,
        stock: 7,
    },
    {
        id:6,
        title: "GPU Gigabyte GeForce RTX3050 OC 8Gb",
        description: "Graphics Processing GeForce RTX™ 3050 Core Clock 1822 MHz (Reference Card: 1777 MHz) CUDA® Cores 2560 Memory Clock 14000 MHz Memory Size 8 GB Memory Type GDDR6 Memory Bus 128 bit Memory Bandwidth (GB/sec) 224 GB/s Card Bus PCI-E 4.0 Digital max resolution 7680×4320 Multi-view 4 Card size L=282 W=117 H=41 mm",
        category: "Videocards",
        price: 550,
        image: '3050.jpg',
        stock: 5,
    },    
    {
        id:7,
        title: "ZOTAC GeForce RTX3050 Twin Edge",
        description: "Obtenga amplificación con la serie ZOTAC GAMING GeForce RTX™ 30 basada en la arquitectura NVIDIA Ampere. Construido con RT Cores y Tensor Cores mejorados, nuevos multiprocesadores de transmisión y memoria GDDR6 de alta velocidad, ZOTAC GAMING GeForce RTX 3050 Twin Edge da lugar a juegos amplificados.",
        category: "Videocards",
        price: 560,
        image: '3050twin.jpg',
        stock: 6,
    },    
    {
        id:8,
        title: "EVGA GeForce RTX3070 FTW3 Ultra 8gb DDR6",
        description: "Obtenga amplificación con la serie ZOTAC GAMING GeForce RTX™ 30 basada en la arquitectura NVIDIA Ampere. Construido con RT Cores y Tensor Cores mejorados, nuevos multiprocesadores de transmisión y memoria GDDR6 de alta velocidad, ZOTAC GAMING GeForce RTX 3050 Twin Edge da lugar a juegos amplificados.",
        category: "Videocards",
        price: 1150,
        image: '3070.jpg',
        stock: 1,
    },    
    {
        id:9,
        title: "GPU Asus GeForce RTX 3070 KO 8GB GDDR6",
        description: "Multiprocesadores NVIDIA Ampere Streaming: Los bloques de construcción para la GPU más rápida y eficiente del mundo, la nueva Ampere SM ofrece el doble de rendimiento de FP32 y una eficiencia energética mejorada. RT Cores de segunda generación: Experimente el doble de rendimiento que los núcleos RT de primera generación, además de RT y sombreado simultáneos para un nivel completamente nuevo de rendimiento de trazado de rayos. Tensor Cores de tercera generación: Obtenga hasta el doble de rendimiento con escasez estructural y algoritmos avanzados de IA como DLSS. Ahora, con soporte para una resolución de hasta 8K, estos núcleos brindan un gran impulso en el rendimiento del juego y capacidades de inteligencia artificial completamente nuevas. El exclusivo diseño de la cubierta presenta llamativas placas frontales doradas y plateadas con detalles ARGB El diseño de ventilador Axial-tech cuenta con un eje de ventilador más pequeño que facilita aspas más largas y un anillo de barrera que aumenta la presión de aire hacia abajo. Los condensadores duraderos duran hasta 2,5 veces más que las tapas convencionales.",
        category: "Videocards",
        price: 1275,
        image: '3070ko.jpg',
        stock: 2,
    },
    {
        id:10,
        title: "GPU Palit GeForce RTX 3080 GameRock 10Gb GDDR6X",
        description: "La serie insignia GameRock de Palit está diseñada para jugadores entusiastas que deseen tener la mejor experiencia de juego y un entorno de iluminación ARGB maximizado. Rediseñada como The Dazzling Angel, la serie GameRock no solo presenta la elegante iluminación Angel ARGB, sino también un módulo térmico increíble que ofrece un rendimiento de enfriamiento extremo.",
        category: "Videocards",
        price: 1650,
        image: '3080.jpg',
        stock: 3,
    },   
    {
        id:11,
        title: "Monitor Samsung LF27T350 FHL 27″ HDMI",
        description: "Ahora, las escenas de acción lucen impecables. Ya sea que estés disfrutando de tu programa televisivo favorito, de un video o videojuego, la frecuencia de actualización de 75 Hz te ofrece una imagen más suave, para un entretenimiento sin retrasos ni efecto fantasma.",
        category: "Monitores",
        price: 280,
        image: 'monitor1.jpg',
        stock: 3,
    },
    {
        id:12,
        title: "Monitor Redragon Ruby 24″ 165hz",
        description: "Cuenta con una increíble pantalla de 23.6 pulgadas, equipada con un panel VA, que brindará una excelente visualización, haciendo que los detalles sean más nítidos y realistas, dando la ventaja necesaria en los momentos cruciales de tus juegos.",
        category: "Monitores",
        price: 295,
        image: 'monitor2.png',
        stock: 3,
    },
    {
        id:13,
        title: "Monitor ASUS TUF VG24VQ Curvo 144hz",
        description: "Monitor de juegos 1500R Full HD (1920 x 1080) de 23.6 pulgadas con frecuencia de actualización ultra rápida de 144Hz diseñada para jugadores profesionales y un juego inmersivo",
        category: "Monitores",
        price: 325,
        image: 'monitor3.png',
        stock: 3,
    },
    {
        id:14,
        title: "Gigabyte G27F 27″ 144hz IPS",
        description: "Tamaño del panel (diagonal) 2 IPS de 7 Área de visualización de pantalla (HxV) 5 97,6 x 336,15 (mm) Tipo / retroiluminación del panel Tipo de borde Superficie de visualización (sin reflejos / reflejos) Sin deslumbramiento Saturación de color 95% DCI-P3 / 125% sRGB",
        category: "Monitores",
        price: 495,
        image: 'monitor4.png',
        stock: 3,
    },
    {
        id:15,
        title: "Monitor ASUS ROG SWIFT PG259QN BK 360Hz G-SYNC IPS HDR",
        description: "El ROG Swift 360 Hz PG259QN es el monitor perfecto para competiciones de eSports y juegos con una acción trepidante. La pantalla FHD (1920 x 1080) cuenta con un panel IPS Fast que ofrece hasta 360 Hz de refresco y un tiempo de respuesta de 1 ms de gris a gris (GTG). El procesador NVIDIA® G-SYNC® produce una acción suave como la seda y un nivel de realismo insólito y su diseño ROG deja patente que no se trata de un monitor de juegos ordinario.",
        category: "Monitores",
        price: 1200,
        image: 'monitor5.jpg',
        stock: 3,
    },
    {
        id:16,
        title: "Nintendo Switch Lite Turquesa",
        description: "La consola Nintendo Switch Lite está diseñada específicamente para el juego portátil, así podrás disfrutar de tus juegos favoritos desde donde quiera que estés.        ",
        category: "Consolas",
        price: 385,
        image: 'nintendolite.jpg',
        stock: 3,
    },
    {
        id:17,
        title: "Nintendo Switch – Animal Crossing: New Horizons Edition",
        description: "Este sistema Nintendo Switch se inspira en el diseño del nuevo juego Animal Crossing: New Horizons, con hermosos controles Joy-Con ™ de color verde pastel y azul que son blancos en la parte posterior, muñequeras blancas y una base de Nintendo Switch blanca, adornada con imágenes reconocibles. personajes Tom Nook y Nooklings Timmy y Tommy.        ",
        category: "Consolas",
        price: 550,
        image: 'nintendoanimal.jpg',
        stock: 3,
    },
    {
        id:18,
        title: "Nintendo Switch – Modelo OLED – Neon",
        description: "La nueva consola cuenta con una vibrante pantalla OLED de 7 pulgadas (17.78 cm), un soporte ajustable y amplio, una base con puerto LAN para conexión por cable, almacenamiento interno de 64 GB y audio mejorado.        ",
        category: "Consolas",
        price: 650,
        image: 'nintendo.jpg',
        stock: 3,
    },
    {
        id:19,
        title: "Microsoft Xbox Serie X – incluye control inalámbrico",
        description: "Equipado con las arquitecturas Zen 2 y RDNA 2 de AMD, el DirectX Ray Tracing ofrece una iluminación, sombras y reflejos precisos y realistas para crear mundos dinámicos y vivos. La Xbox Series X ofrece velocidades de cuadro sensacionalmente suaves de hasta 120 FPS con la explosión visual que ofrece HDR. Sumérgete con personajes más nítidos, mundos más brillantes y detalles imposibles con auténtico 4K.",
        category: "Consolas",
        price: 1000,
        image: 'xbox.jpg',
        stock: 3,
    },
    {
        id:20,
        title: "Sony PlayStation 5 Standard Horizon Edition",
        description: "-Procesador de 8 núcleos 3.5 GHz AMD Zen 2. -GPU de 10.3 teraflop AMD RDNA 2.-16 GB GDDR6 de memoria RAM.-825GB SSD de velocidad ultrarrápida para almacenamiento.-Lectora De Discos Amv-Juega tus títulos de PS5 favoritos en tu impresionante televisor 4K.-Hasta 120 fps con salida de 120 Hz.-Tecnología HDR.-Compatibilidad con 8K con HDMI 2.1.",
        category: "Consolas",
        price: 1300,
        image: 'play5.jpg',
        stock: 5,
    },
    {
        id:21,
        title: "AMD Ryzen 5 3600",
        description: "# de núcleos de CPU 6 # de hilos 12Reloj base 3.6GHzReloj de aumento máx. 4.2GHzCaché L1 total 64KBCaché L2 total 3MBCaché L3 total 32MBDesbloqueados SíCMOS TSMC 7nm FinFETPackage AM4 Versión de PCI Express PCIe 4.0 x16Solución térmica Wraith StealtTDP/TDP predeterminado 65WTemp. máx. 95°C",
        category: "Procesadores",
        price: 215,
        image: 'ryzen5.jpg',
        stock: 5,
    },
    {
        id:22,
        title: "AMD Ryzen 7 5700G con Gráficos Radeon",
        description: "-N.° de núcleos de CPU 8 N.° de subprocesos 16N.° de núcleos de GPU 8Reloj base 3.8GHz Reloj de aumento máx. Hasta 4.6GHzCaché L2 total 4MBCaché L3 total 16MBDesbloqueados SíCMOS TSMC 7nm FinFETPaquete AM4Versión de PCI Express PCIe® 3.0Solución térmica Wraith StealthTDP/TDP predeterminado 65WcTDP 45-65WTemp. máx. 95°CVelocidad máxima de memoria Up to 3200MHzTipo de memoria DDR4Canales de memoria 2",
        category: "Procesadores",
        price: 465,
        image: 'ryzen72.jpg',
        stock: 5,
    },
    {
        id:23,
        title: "CPU AMD Ryzen 7 5800X AM4",
        description: "# de núcleos de CPU 6 # de hilos 12Reloj base 3.7GHzReloj de aumento máx. Hasta 4.6GHzCaché L2 total 3MBCaché L3 total 32MBDesbloqueados SíCMOS TSMC 7nm FinFETPackage AM4Versión de PCI Express PCIe 4.0Solución térmica (PIB) Wraith StealthTDP/TDP predeterminado 65W",
        category: "Procesadores",
        price: 525,
        image: 'ryzen7.jpg',
        stock: 5,
    },
    {
        id:24,
        title: "AMD Ryzen 9 5900X AM4",
        description: "# de núcleos de CPU 12 # de hilos 24Reloj base 3.7GHzReloj de aumento máx. Hasta 4.8GHzCaché L2 total 6MBCaché L3 total 64MBDesbloqueados SíCMOS TSMC 7nm FinFETPackage AM4Versión de PCI Express PCIe 4.0Solución térmica (PIB) Wraith StealthTDP/TDP predeterminado 105W",
        category: "Procesadores",
        price: 640,
        image: 'ryzen92.jpg',
        stock: 5,
    },
    {
        id:25,
        title: "CPU AMD Ryzen 9 5950X AM4",
        description: "# de núcleos de CPU 16 # de hilos 32Reloj base 3.4GHzReloj de aumento máx. Hasta 4.9GHzCaché L2 total 8MBCaché L3 total 64MBDesbloqueados SíCMOS TSMC 7nm FinFETPackage AM4Versión de PCI Express PCIe 4.0Solución térmica (PIB) Wraith StealthTDP/TDP predeterminado 105W",
        category: "Procesadores",
        price: 989,
        image: 'ryzen9.jpg',
        stock: 5,
    },
    {
        id:26,
        title: "Silla HHGears XL 300 Series Black and White",
        description: "La silla para juegos XL-300 está diseñada para aquellos que desean agregar un toque de estilo a su configuración. La elección del material de calidad se extiende por toda la silla con un soporte de peso de hasta 150 kg, un marco de acero duradero y una base de aleación de metal para completar la construcción.",
        category: "Sillas Gamer",
        price: 235,
        image: 'silla hhgears.jpg',
        stock: 5,
    },
    {
        id:27,
        title: "Silla Cougar Fusion Black",
        description: "Listo para juegos y uso profesional, FUSION es una cómoda silla giratoria construida con materiales de alta calidad y con un poderoso diseño COUGAR.",
        category: "Sillas Gamer",
        price: 289,
        image: 'sillacougar.jpg',
        stock: 5,
    },
    {
        id:28,
        title: "Silla Cougar Gaming Armor ONE",
        description: "COUGAR ARMOR ONE le ofrece la comodidad que necesita para disfrutar plenamente de largas sesiones de juego. Totalmente ajustable y fabricada con materiales de primera calidad, esta silla para juegos presenta también el diseño exclusivo COUGAR que se ha convertido en un signo de la pasión por los juegos.",
        category: "Sillas Gamer",
        price: 360,
        image: 'sillaarmor.png',
        stock: 5,
    },
    {
        id:29,
        title: "Cougar Ranger Gaming Sofa Recliner",
        description: "Ranger ofrece la gama completa de comodidad para jugadores de consola, jugadores móviles, jugadores portátiles o jugadores de PC. Utilizamos materiales de primera calidad, como estructura de acero, componentes de alta calidad, reposapiés plegable y respaldo inclinado. Ranger le brinda la comodidad que necesita para disfrutar plenamente de largas sesiones de juego. ¡Ranger está listo para luchar!",
        category: "Sillas Gamer",
        price: 540,
        image: 'sillon.jpg',
        stock: 5,
    },
    {
        id:30,
        title: "Silla Cougar Argo Orange",
        description: "Argo está construida con un marco de aluminio de primera calidad. Contiene una almohadilla de malla altamente transpirable que ofrece el máximo apoyo duradero para una experiencia de juego más cómoda.        ",
        category: "Sillas Gamer",
        price: 774,
        image: 'cougar.jpg',
        stock: 5,
    },
    
]

export default products;