const products = [
    {
        id:1,
        title: "Equipo AMD Athlon 3000G Gamer – Radeon™ Vega 3 Graphics",
        description: "Gabinete Perseo Cp3 Rgb. Fuente Eagle Warrior 600w 80 Plus. Biostar A320 – Sata III – USB 3.0. Procesador AMD Athlon 3000G 3,5Ghz 2 núcleos – 4 hilos. Memoria Kingston 8Gb DDR4 3200mhz. Disco WD/Seagate 1TBGráficos Radeon™ Vega 3",
        category: "Computers",
        price: 375,
        image: 'amd0.jpg',
        stock: 6,
    },
    {
        id:2,
        title: "Equipo AMD Ryzen 5 5500 Full Gamer – 16gb – SSD – RX6500XT",
        description: "Gabinete EAGLE WARRIOR LOOP RGB con fan trasero Fuente TC ARMY 500w 80 Plus Mother Asrock / Biostar B550MH – Sata III – USB 3.0 Procesador AMD Ryzen 5 5500 6 núcleos 12 hilos 3.6GHz / 4.2GHz Memoria Kingston 16Gb DDR4 3200mhz (2×8) Disco SSD 240Gb + Seagate / WD sata III 1Tb Gráficos Radeon RX6500XT",
        category: "Computers",
        price: 1075,
        image: 'amd2.jpg',
        stock: 10,
    },
    {
        id:3,
        title: "Equipo Intel Core I5 11400f Pro Gamer – 16Gb 3200mhz – SSD – RTX3050",
        description: "Gabinete Antec NX220 ARGB + fan con Led Fuente Antec CSK 550w 80 Plus Bronze Mother Gigabyte / Biostar B550 4 bancos de memoria –  soporte SSD PCIe – Sata III – USB 3.0 Procesador AMD Ryzen 5 5600X 3,7 / 4,6Ghz 6 núcleos – 12 hilos Memoria Kingston 16Gb DDR4 3200mhz (2 x 8Gb) Disco SSD 240  + WD Sata III 1Tb Gráficos Geforce RTX2060",
        category: "Computers",
        price: 1250,
        image: 'amd1.jpg',
        stock: 20,
    },
    {
        id:4,
        title: "Equipo AMD Ryzen 5 5600X Full Gamer – 16gb – SSD – RTX3060",
        description: "Gabinete Antec NX220 ARGB + fan con Led Fuente Antec CSK 650w 80 Plus Bronze Mother Gigabyte / Biostar B550 4 bancos de memoria –  soporte SSD PCIe – Sata III – USB 3.0 Procesador AMD Ryzen 5 5600X 3,7 / 4,6Ghz 6 núcleos – 12 hilos Memoria Kingston 16Gb DDR4 3200mhz (2 x 8Gb) Disco SSD 240  + WD Sata III 1Tb Gráficos Radeon RX6600XT",
        category: "Computers",
        price: 1650,
        image: 'amd3.jpg',
        stock: 13,
    },
    {
        id:5,
        title: "Equipo AMD Ryzen 9 5900X Full Gamer 32gb + SSD + RTX3080",
        category: "Computers",
        description: "Gabinete Antec NX800 ARGB – incluye 3 fanes Fuente Cooler Master MWE 850W 80 Plus Gold Full Modular Mother Asus TUF B550M Gaming con 4 bancos DDR4 hasta 128Gb – soporte m.2 PCIe Procesador AMD Ryzen 9 5900X 12 núcleos 24 hilos 3,7 / 4,8Ghz + Watercooling Antec Neptune 240 Memoria Kingston Fury Beast 32Gb DDR4 3200mhz (2 x 16Gb) Disco SSD 1Tb M.2 PCIe Gráficos Geforce RTX3080",
        price: 3500,
        image: 'amd4.jpg',
        stock: 7,
    },
    {
        id:6,
        title: "GPU Gigabyte GeForce RTX3050 OC 8Gb",
        description: "Graphics Processing GeForce RTX™ 3050 Core Clock 1822 MHz (Reference Card: 1777 MHz) CUDA® Cores 2560 Memory Clock 14000 MHz Memory Size 8 GB Memory Type GDDR6 Memory Bus 128 bit Memory Bandwidth (GB/sec) 224 GB/s Card Bus PCI-E 4.0 Digital max resolution 7680×4320 Multi-view 4 Card size L=282 W=117 H=41 mm",
        category: "Videocards",
        price: 550,
        image: '3050.jpg',
        stock: 5,
    },    
    {
        id:7,
        title: "ZOTAC GeForce RTX3050 Twin Edge",
        description: "Obtenga amplificación con la serie ZOTAC GAMING GeForce RTX™ 30 basada en la arquitectura NVIDIA Ampere. Construido con RT Cores y Tensor Cores mejorados, nuevos multiprocesadores de transmisión y memoria GDDR6 de alta velocidad, ZOTAC GAMING GeForce RTX 3050 Twin Edge da lugar a juegos amplificados.",
        category: "Videocards",
        price: 560,
        image: '3050twin.jpg',
        stock: 6,
    },    
    {
        id:8,
        title: "EVGA GeForce RTX3070 FTW3 Ultra 8gb DDR6",
        description: "Obtenga amplificación con la serie ZOTAC GAMING GeForce RTX™ 30 basada en la arquitectura NVIDIA Ampere. Construido con RT Cores y Tensor Cores mejorados, nuevos multiprocesadores de transmisión y memoria GDDR6 de alta velocidad, ZOTAC GAMING GeForce RTX 3050 Twin Edge da lugar a juegos amplificados.",
        category: "Videocards",
        price: 1150,
        image: '3070.jpg',
        stock: 1,
    },    
    {
        id:9,
        title: "GPU Asus GeForce RTX 3070 KO 8GB GDDR6",
        description: "Multiprocesadores NVIDIA Ampere Streaming: Los bloques de construcción para la GPU más rápida y eficiente del mundo, la nueva Ampere SM ofrece el doble de rendimiento de FP32 y una eficiencia energética mejorada. RT Cores de segunda generación: Experimente el doble de rendimiento que los núcleos RT de primera generación, además de RT y sombreado simultáneos para un nivel completamente nuevo de rendimiento de trazado de rayos. Tensor Cores de tercera generación: Obtenga hasta el doble de rendimiento con escasez estructural y algoritmos avanzados de IA como DLSS. Ahora, con soporte para una resolución de hasta 8K, estos núcleos brindan un gran impulso en el rendimiento del juego y capacidades de inteligencia artificial completamente nuevas. El exclusivo diseño de la cubierta presenta llamativas placas frontales doradas y plateadas con detalles ARGB El diseño de ventilador Axial-tech cuenta con un eje de ventilador más pequeño que facilita aspas más largas y un anillo de barrera que aumenta la presión de aire hacia abajo. Los condensadores duraderos duran hasta 2,5 veces más que las tapas convencionales.",
        category: "Videocards",
        price: 1275,
        image: '3070ko.jpg',
        stock: 2,
    },
    {
        id:10,
        title: "GPU Palit GeForce RTX 3080 GameRock 10Gb GDDR6X",
        description: "La serie insignia GameRock de Palit está diseñada para jugadores entusiastas que deseen tener la mejor experiencia de juego y un entorno de iluminación ARGB maximizado. Rediseñada como The Dazzling Angel, la serie GameRock no solo presenta la elegante iluminación Angel ARGB, sino también un módulo térmico increíble que ofrece un rendimiento de enfriamiento extremo.",
        category: "Videocards",
        price: 1650,
        image: '3080.jpg',
        stock: 3,
    },   
    {
        id:11,
        title: "Monitor Samsung LF27T350 FHL 27″ HDMI",
        description: "Ahora, las escenas de acción lucen impecables. Ya sea que estés disfrutando de tu programa televisivo favorito, de un video o videojuego, la frecuencia de actualización de 75 Hz te ofrece una imagen más suave, para un entretenimiento sin retrasos ni efecto fantasma.",
        category: "Monitores",
        price: 280,
        image: 'monitor1.jpg',
        stock: 3,
    },
    {
        id:12,
        title: "Monitor Redragon Ruby 24″ 165hz",
        description: "Cuenta con una increíble pantalla de 23.6 pulgadas, equipada con un panel VA, que brindará una excelente visualización, haciendo que los detalles sean más nítidos y realistas, dando la ventaja necesaria en los momentos cruciales de tus juegos.",
        category: "Monitores",
        price: 295,
        image: 'monitor2.png',
        stock: 3,
    },
    {
        id:13,
        title: "Monitor ASUS TUF VG24VQ Curvo 144hz",
        description: "Monitor de juegos 1500R Full HD (1920 x 1080) de 23.6 pulgadas con frecuencia de actualización ultra rápida de 144Hz diseñada para jugadores profesionales y un juego inmersivo",
        category: "Monitores",
        price: 325,
        image: 'monitor3.png',
        stock: 3,
    },
    {
        id:14,
        title: "Gigabyte G27F 27″ 144hz IPS",
        description: "Tamaño del panel (diagonal) 2 IPS de 7 Área de visualización de pantalla (HxV) 5 97,6 x 336,15 (mm) Tipo / retroiluminación del panel Tipo de borde Superficie de visualización (sin reflejos / reflejos) Sin deslumbramiento Saturación de color 95% DCI-P3 / 125% sRGB",
        category: "Monitores",
        price: 495,
        image: 'monitor4.png',
        stock: 3,
    },
    {
        id:15,
        title: "Monitor ASUS ROG SWIFT PG259QN BK 360Hz G-SYNC IPS HDR",
        description: "El ROG Swift 360 Hz PG259QN es el monitor perfecto para competiciones de eSports y juegos con una acción trepidante. La pantalla FHD (1920 x 1080) cuenta con un panel IPS Fast que ofrece hasta 360 Hz de refresco y un tiempo de respuesta de 1 ms de gris a gris (GTG). El procesador NVIDIA® G-SYNC® produce una acción suave como la seda y un nivel de realismo insólito y su diseño ROG deja patente que no se trata de un monitor de juegos ordinario.",
        category: "Monitores",
        price: 1200,
        image: 'monitor5.jpg',
        stock: 3,
    },
]

export default products;